[project]
name = "sxzslz-flask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbutils>=3.1.1",
    "flask>=3.1.1",
    "flask-wtf>=1.2.2",
    "pydantic>=2.11.7",
    "pymysql>=1.1.1",
    "pytest>=8.4.1",
]
